project:
  type: book
  output-dir: docs
  

book:
  title: "Statistical Computing"
  author:   
  - name: Isaac Quintanilla Salinas
    url: https://www.inqs.info
    orcid: 0000-0002-1137-4310

  chapters:
    - index.qmd
    - preface.qmd
    - part: r.qmd
      chapters: 
        - basics.qmd
        - control_flow.qmd
        - functional.qmd
        - scripting.qmd
    - part: permutations.qmd
      chapters:
        - perm_hyp.qmd
        - perm_reg.qmd
    - part: mc.qmd
      chapters:
        - simulations.qmd
        - mc_int.qmd
        - mc_testing.qmd
    - part: bootstrapping.qmd
      chapters:
        - parametric.qmd
        - nonparametric.qmd
    - part:  da.qmd
      chapters: 
        - importing.qmd
        - data_manip.qmd
        - data_summary.qmd
        - plot.qmd
    - part: reporting.qmd
      chapters: 
        - documents.qmd
        - notebooks.qmd
        - presentations.qmd
    - part: efficient.qmd
      chapters: 
        - debugging.qmd
        - profiling.qmd
        - vectorizing.qmd
        - rcpp.qmd



  sidebar:
    style: docked
    background: light
  repo-url: https://github.com/inqs909/stat_comp/
  downloads: [pdf, epub]


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default

editor: source

comments:
  hypothesis: true
