project:
  type: book
  output-dir: docs
  resources:
    - "files"
    - "data"

execute:
  freeze: auto

book:
  title: "Statistical Computing"
  author:   
  - name: Isaac Quintanilla Salinas
    url: https://www.inqs.info
    orcid: 0000-0002-1137-4310

  chapters:
    - index.qmd
    - preface.qmd
    - part: probstats.qmd
      chapters:
        - rv.qmd
        - models.qmd
        - stats.qmd
    - part: monte_carlo.qmd
      chapters: 
        - mc.qmd
        - mcmc.qmd
        - mc_int.qmd
    - part: permutations.qmd
      chapters:
        - perm_hyp.qmd
        - perm_reg.qmd
    - part: bootstrapping.qmd
      chapters:
        - parametric.qmd
        - nonparametric.qmd
    - part: simulations.qmd
      chapters:
        - mc_testing.qmd
        - mc_reg.qmd
        - mc_power.qmd
    - part: r.qmd
      chapters: 
        - basics.qmd
        - data_summary.qmd
        - plot.qmd
        - control_flow.qmd
        - functional.qmd
        - scripting.qmd
        - resources.qmd



  sidebar:
    style: docked
    background: light
  repo-url: https://github.com/inqs909/stat_comp/
  downloads: [pdf, epub]


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  epub: default

editor: source

comments:
  hypothesis: true
  
citation: true
