# Introduction {.unnumbered}

Welcome to Statistical Computing! A book designed to give undergraduate students exposure to several topics related to computational statistics and programming in R.

::: callout-note
This book is a work in progress and will contain several grammatical errors and unfinished chapters. The final product is expected to be ready by the 2026-27 Academic Year.
:::

This work is published under a [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) license. 


### Installing R

[R](https://www.r-project.org/) is an open-source programming language used to conduct statistical analysis.
You can freely download and install R [here](https://cloud.r-project.org/).

### Installing Positron

[Positron](https://positron.posit.co/start.html) is an Integrated Development Environment ([IDE](https://en.wikipedia.org/wiki/Integrated_development_environment)) used for data science. It contains several tools needed to extend your programming and project management skills. 

You can download and install the open-source (free) version of Positron [here](https://positron.posit.co/download.html).

### Installing Quarto

[Quarto](https://quarto.org/) is a technical documentation system that allows you to embed narrative, code, and output in one document.
Quarto should be automatically install from Positron; however, you can update (or install) it [here](https://quarto.org/docs/get-started/).

### Installing R Packages

R Packages extends the functionality from the base functions in R. R packages contain extra functions to conduct uncommon statistical models.

The [tidyverse](https://www.tidyverse.org/) is a set of comprehensive packages to prepare and analyze data. To install tidyverse, use the following line in the console:


```{r}
#| echo: true
#| eval: false

install.packages("tidyverse")

```


### Topics

|Topic | Description |
|:-|:-|
| Probability and Statistics | A review of different topics related to probability theory and statistics. |
|Monte Carlo Methods | Explore different algorithms to generate random variables. |
|Randomizations | Learn how to implement different permutation tests. |
|Bootstrapping | Conduct different bootstrapping techniques to construct confidence intervals. |
|Simulations | Implement Monte Carlo methods to approximate hypothesis tests, simulation studies, and power analysis. |
|R Programming | Provide with a brief introduction to R programming. Topics include basic computations, control flow statements, functional programming, scripting, summarization and plotting|
 

